### ISSUE TITLE
problem with reading secrets

### ISSUE THREAD

**Issue by zioproto** [zioproto/github-issues-ai-assistant#10]
I will demonstrate that you cannot read the secrets when triggering the issue with:

```
on:
  issues:
    types: [opened, edited]
```

this is the full code:

```
name: My Workflow
permissions: write-all
on:
  issues:
    types: [opened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action
      uses: zioproto/github-issues-ai-assistant@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue_number: ${{ github.event.issue.number }}
        #issue_number: ${{ inputs.issue_number }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
```
